# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: https://mjsamberg.github.io/git-courseware
title: Courses

# NC State-specific items for the NCSU branding bar
ncstate_brand_search_code: 018149703590495268473:u8ozjjclv58
ncstate_brand_search_placeholder: Search ncsu.edu

#College/Org Information
#Org/College Name
org_name: College Of Education
org_url: https://ced.ncsu.edu
#Unit/Department name
unit_name_long: "Department of Teacher Education and Learning Sciences"
unit_url: https://ced.ncsu.edu/tels
address: "1890 Main Campus Drive<br/>Raleigh, NC 27606"
phone: "919.513.8551"
email: "mjsamber@ncsu.edu"


description: >- # this means to ignore newlines until "baseurl:"
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

#Social media links
facebook_username: mjsamberg
twitter_username: mjsamberg
github_username:  mjsamberg

#URL For this repository
repository_url: https://github.com/mjsamberg/courses
theme: git-courseware

#Site-specific information
nav_showcourses: 1 #Show all courses in the nav bar.

# A list of the pages to display in the navigation bar
header_pages:
  - title: Wolfware
	url: https://wolfware.ncsu.edu
	absolute: true
  - title: Home
	url: /
	
footer_pages: 
  # - title: Home
  #   url: /
  # - title: Friday Institute
  #   url: https://www.fi.ncsu.edu
  #   absolute: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh